### ISSUE TITLE
右框解密失败

### ISSUE THREAD

**Issue by sifanx** [TanixLu/EasySafeChat#1]
https://user-images.githubusercontent.com/42561369/231375645-3a6200a2-ac7c-4a7e-ab48-04698b891386.mp4

这个是BUG，还是本来就不允许这么操作？如果不允许这么操作，那岂不是可以把右框那个向左的按钮去掉？

**Comment by sifanx** [comment]
把箭头改成“加密”、“解密” 看起来更直观

**Comment by sifanx** [comment]
![20230413083409](https://user-images.githubusercontent.com/42561369/231615409-c742f6c9-e213-4588-bfb8-c8454220b6da.jpg)

把此处改掉可以了

**Comment by sifanx** [comment]
https://user-images.githubusercontent.com/42561369/231615663-c13fa1ad-a99a-440c-bac9-b97f4f613ba3.mp4

**Comment by TanixLu** [comment]
抱歉现在才回复，我才发现这个仓库有个issue。
两人交流，获取的一般只是对方的公钥，所以右框只会存公钥，因此是没有解密功能的。
至于我使用箭头而不是中文，我觉得使用箭头会使界面看起来更简洁、协调。
我准备提交一个commit，将右框的左箭头（解密）删掉；另外，自己的私钥放在文本框里，太容易手滑复制给别人了，因此我准备将`MyKeys.txt`改成`MyPrivateKey.txt`和`MyPublicKey.txt`两部分，文本框只加载公钥。
